FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY backend/package*.json ./backend/
COPY frontend/package*.json ./frontend/
COPY agents/package*.json ./agents/
COPY shared/package*.json ./shared/
RUN npm ci

COPY agents ./agents
COPY shared ./shared

CMD ["npm", "run", "dev", "-w", "agents"]
