import { Octokit } from '@octokit/rest'
import pg          from 'pg'

const { Pool } = pg

function getPool() {
  return new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: (process.env.DATABASE_URL?.includes("localhost") || process.env.DB_SSL === "false") ? false : { rejectUnauthorized: false },
    max: 3,
  })
}

export async function createFixPR({ owner, repo, baseBranch = 'main', fixes, findings, userId, jobId }) {
  const pool = getPool()
  const { rows } = await pool.query(
    'SELECT github_token FROM users WHERE id = $1', [userId]
  )
  await pool.end()

  const octokit    = new Octokit({ auth: rows[0]?.github_token })
  const branchName = `intelliCodeRev/security-fix-${Date.now()}`

  // Create branch
  const { data: baseRef } = await octokit.git.getRef({ owner, repo, ref: `heads/${baseBranch}` })
  await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: baseRef.object.sha })
  console.log(`Created branch ${branchName}`)

  // Apply each fix
  const applied = []
  for (const fix of fixes) {
    try {
      const { data: current } = await octokit.repos.getContent({
        owner, repo, path: fix.filePath, ref: branchName,
      })
      await octokit.repos.createOrUpdateFileContents({
        owner, repo,
        path:    fix.filePath,
        message: `fix(security): ${fix.title}\n\nFixes ${fix.cwe ?? 'security issue'} in ${fix.filePath}`,
        content: Buffer.from(fix.fixedContent).toString('base64'),
        sha:     current.sha,
        branch:  branchName,
      })
      applied.push(fix)
      console.log(`Applied fix → ${fix.filePath}`)
    } catch (err) {
      console.error(`Failed to apply ${fix.filePath}:`, err.message)
    }
  }

  if (applied.length === 0) throw new Error('No fixes could be applied to the repo')

  // Ensure labels exist
  for (const label of [
    { name: 'security',       color: 'e11d48', description: 'Security fix' },
    { name: 'intelliCodeRev-autofix', color: '7c3aed', description: 'Auto-generated by IntelliCodeRev' },
  ]) {
    try { await octokit.issues.createLabel({ owner, repo, ...label }) }
    catch {}
  }

  const critical = findings.filter(f => f.severity === 'critical').length
  const warnings = findings.filter(f => f.severity === 'warning').length

  const fixList = applied.map((fix, i) => `
### Fix ${i + 1}: ${fix.title}
**File:** \`${fix.filePath}\` **Severity:** ${fix.severity} **CWE:** ${fix.cwe ?? 'N/A'}

${fix.description ?? ''}

**Change:** ${fix.rationale}
---`).join('\n')

  const body = `## IntelliCodeRev Automated Security Fix

> **This PR requires human review before merging. IntelliCodeRev never auto-merges.**

| | Count |
|---|---|
| Critical | ${critical} |
| Warnings | ${warnings} |
| Files changed | ${applied.length} |
| Job ID | \`${jobId}\` |

## Fixes
${fixList}

---
*Generated by IntelliCodeRev — multi-agent security scanner.*
*All fixes passed QA-Checker verification and AST syntax validation.*`

  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `[IntelliCodeRev] ${applied.length} security fix${applied.length > 1 ? 'es' : ''} — ${critical} critical, ${warnings} warnings`,
    body,
    head: branchName,
    base: baseBranch,
  })

  await octokit.issues.addLabels({
    owner, repo, issue_number: pr.number, labels: ['security', 'intelliCodeRev-autofix'],
  })

  console.log(`PR #${pr.number} → ${pr.html_url}`)
  return { prNumber: pr.number, prUrl: pr.html_url, branchName, appliedFixes: applied.length }
}
